function correspondingFitInLS = CorrespondingFunctionInLinearSpace( ...
    fittingInLogSpace, linearFunction, coefficients)

    %
    % Chang Chang, Simone Bianco, Ashley Acevedo, Chao Tang, Raul Andino.
    % Genetic interactions shaping evolutionary trajectories in an RNA virus
    % population. bioRxiv, 2020, https://doi.org/10.1101/2020.01.16.908129
    %
    
    if ( length(coefficients) == 1) 
        correspondingFitInLS = cfit(linearFunction, ...
            getfield(fittingInLogSpace, coefficients{1}));
    elseif ( length(coefficients) == 2) 
        correspondingFitInLS = cfit(linearFunction, ...
            getfield(fittingInLogSpace, coefficients{1}), ...
            getfield(fittingInLogSpace, coefficients{2}));
    elseif ( length(coefficients) == 3) 
        correspondingFitInLS = cfit(linearFunction, ...
            getfield(fittingInLogSpace, coefficients{1}), ...
            getfield(fittingInLogSpace, coefficients{2}), ...
            getfield(fittingInLogSpace, coefficients{3}));
    elseif ( length(coefficients) == 4) 
        correspondingFitInLS = cfit(linearFunction, ...
            getfield(fittingInLogSpace, coefficients{1}), ...
            getfield(fittingInLogSpace, coefficients{2}), ...
            getfield(fittingInLogSpace, coefficients{3}), ...
            getfield(fittingInLogSpace, coefficients{4}));
    elseif ( length(coefficients) == 5) 
        correspondingFitInLS = cfit(linearFunction, ...
            getfield(fittingInLogSpace, coefficients{1}), ...
            getfield(fittingInLogSpace, coefficients{2}), ...
            getfield(fittingInLogSpace, coefficients{3}), ...
            getfield(fittingInLogSpace, coefficients{4}), ...
            getfield(fittingInLogSpace, coefficients{5}));
    elseif ( length(coefficients) == 6) 
        correspondingFitInLS = cfit(linearFunction, ...
            getfield(fittingInLogSpace, coefficients{1}), ...
            getfield(fittingInLogSpace, coefficients{2}), ...
            getfield(fittingInLogSpace, coefficients{3}), ...
            getfield(fittingInLogSpace, coefficients{4}), ...
            getfield(fittingInLogSpace, coefficients{5}), ...
            getfield(fittingInLogSpace, coefficients{6}));
    else
        error('Too many coefficients.')
    end
end
